baseURL: https://keenan-roe.netlify.app/
title: Website of Keenan Roe
theme: hugo-theme-m10c
paginate: 8
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 2
    - identifier: about
      name: About
      url: /about/
      weight: 3
    - identifier: resume
      name: Resume
      url: /resume/
      weight: 3
params:
  author: Keenan Roe
  description: A future data scientist learning more every day.
  menu_item_separator: ' - '
  social:
    - icon: github
      name: Github
      url: https://github.com/Keenan-Roe
    - icon: twitter
      name: Twitter
      url: https://twitter.com/Keenan_Roe
    - icon: mail
      name: email
      url: mailto:keenan.roe@hotmail.com
    style:
      darkestColor = "#d35050"
      darkColor = "#212121"
      lightColor = "#f5e3e0"
      lightestColor = "#f5f5f5"
      primaryColor = "#ffffff"
